name = "site-advocatai"
main = "worker.ts"
compatibility_date = "2024-12-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
