// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/leads": {
    params: {};
  };
  "/admin/content": {
    params: {};
  };
  "/admin/calendar": {
    params: {};
  };
  "/admin/media": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/email": {
    params: {};
  };
  "/admin/seo": {
    params: {};
  };
  "/admin/admins": {
    params: {};
  };
  "/admin/backup": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/:lang": {
    params: {
      "lang": string;
    };
  };
  "/:lang/:page": {
    params: {
      "lang": string;
      "page": string;
    };
  };
  "/:lang/:page/:category": {
    params: {
      "lang": string;
      "page": string;
      "category": string;
    };
  };
  "/:lang/:page/:category/:slug": {
    params: {
      "lang": string;
      "page": string;
      "category": string;
      "slug": string;
    };
  };
  "/:lang/:page/:id": {
    params: {
      "lang": string;
      "page": string;
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/leads" | "/admin/content" | "/admin/calendar" | "/admin/media" | "/admin/analytics" | "/admin/email" | "/admin/seo" | "/admin/admins" | "/admin/backup" | "/admin/settings" | "/admin/login" | "/:lang" | "/:lang/:page" | "/:lang/:page/:category" | "/:lang/:page/:category/:slug" | "/:lang/:page/:id";
  };
  "admin/layouts/AdminLayout.tsx": {
    id: "admin/layouts/AdminLayout";
    page: "/admin" | "/admin/leads" | "/admin/content" | "/admin/calendar" | "/admin/media" | "/admin/analytics" | "/admin/email" | "/admin/seo" | "/admin/admins" | "/admin/backup" | "/admin/settings";
  };
  "admin/pages/AdminDashboard.tsx": {
    id: "admin/pages/AdminDashboard";
    page: "/admin";
  };
  "admin/pages/AdminLeads.tsx": {
    id: "admin/pages/AdminLeads";
    page: "/admin/leads";
  };
  "admin/pages/AdminContent.tsx": {
    id: "admin/pages/AdminContent";
    page: "/admin/content";
  };
  "admin/pages/AdminCalendar.tsx": {
    id: "admin/pages/AdminCalendar";
    page: "/admin/calendar";
  };
  "admin/pages/AdminMedia.tsx": {
    id: "admin/pages/AdminMedia";
    page: "/admin/media";
  };
  "admin/pages/AdminAnalytics.tsx": {
    id: "admin/pages/AdminAnalytics";
    page: "/admin/analytics";
  };
  "admin/pages/AdminEmail.tsx": {
    id: "admin/pages/AdminEmail";
    page: "/admin/email";
  };
  "admin/pages/AdminSEO.tsx": {
    id: "admin/pages/AdminSEO";
    page: "/admin/seo";
  };
  "admin/pages/AdminAdmins.tsx": {
    id: "admin/pages/AdminAdmins";
    page: "/admin/admins";
  };
  "admin/pages/AdminBackup.tsx": {
    id: "admin/pages/AdminBackup";
    page: "/admin/backup";
  };
  "admin/pages/AdminSettings.tsx": {
    id: "admin/pages/AdminSettings";
    page: "/admin/settings";
  };
  "admin/pages/AdminLogin.tsx": {
    id: "admin/pages/AdminLogin";
    page: "/admin/login";
  };
  "routes/home-redirect.tsx": {
    id: "routes/home-redirect";
    page: "/";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/:lang";
  };
  "routes/dispatcher.tsx": {
    id: "dispatcher-1";
    page: "/:lang/:page";
  } | {
    id: "dispatcher-2";
    page: "/:lang/:page/:category";
  } | {
    id: "dispatcher-3";
    page: "/:lang/:page/:category/:slug";
  } | {
    id: "dispatcher-4";
    page: "/:lang/:page/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "admin/layouts/AdminLayout": typeof import("./app/admin/layouts/AdminLayout.tsx");
  "admin/pages/AdminDashboard": typeof import("./app/admin/pages/AdminDashboard.tsx");
  "admin/pages/AdminLeads": typeof import("./app/admin/pages/AdminLeads.tsx");
  "admin/pages/AdminContent": typeof import("./app/admin/pages/AdminContent.tsx");
  "admin/pages/AdminCalendar": typeof import("./app/admin/pages/AdminCalendar.tsx");
  "admin/pages/AdminMedia": typeof import("./app/admin/pages/AdminMedia.tsx");
  "admin/pages/AdminAnalytics": typeof import("./app/admin/pages/AdminAnalytics.tsx");
  "admin/pages/AdminEmail": typeof import("./app/admin/pages/AdminEmail.tsx");
  "admin/pages/AdminSEO": typeof import("./app/admin/pages/AdminSEO.tsx");
  "admin/pages/AdminAdmins": typeof import("./app/admin/pages/AdminAdmins.tsx");
  "admin/pages/AdminBackup": typeof import("./app/admin/pages/AdminBackup.tsx");
  "admin/pages/AdminSettings": typeof import("./app/admin/pages/AdminSettings.tsx");
  "admin/pages/AdminLogin": typeof import("./app/admin/pages/AdminLogin.tsx");
  "routes/home-redirect": typeof import("./app/routes/home-redirect.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "dispatcher-1": typeof import("./app/routes/dispatcher.tsx");
  "dispatcher-2": typeof import("./app/routes/dispatcher.tsx");
  "dispatcher-3": typeof import("./app/routes/dispatcher.tsx");
  "dispatcher-4": typeof import("./app/routes/dispatcher.tsx");
};